### ISSUE TITLE
Deploy to cloud button fails. Can't find banking.json to upload

### ISSUE THREAD

**Issue by markstur** [IBM/watson-banking-chatbot#113]
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR fs.js:114
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     throw err;
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     ^
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR Error: ENOENT: no such file or directory, open 'data/conversation/workspaces/banking.json'
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Object.openSync (fs.js:443:3)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Object.readFileSync (fs.js:343:35)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Object.<anonymous> (/home/vcap/app/app.js:93:37)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Module._compile (internal/modules/cjs/loader.js:776:30)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Module.load (internal/modules/cjs/loader.js:653:32)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at Module.require (internal/modules/cjs/loader.js:690:17)
2019-08-23T14:00:56.16-0700 [APP/PROC/WEB/0]ERR     at require (internal/modules/cjs/helpers.js:25:18)
2019-08-23T14:00:56.17-0700 [APP/PROC/WEB/0]ERR npm ERR! code ELIFECYCLE
2019-08-23T14:00:56.17-0700 [APP/PROC/WEB/0]ERR npm ERR! errno 1
2019-08-23T14:00:56.17-0700 [APP/PROC/WEB/0]ERR npm ERR! watson-banking-chatbot@0.0.1 start: `node server.js`
2019-08-23T14:00:56.17-0700 [APP/PROC/WEB/0]ERR npm ERR! Exit status 1
2019-08-23T14:00:56.17-0700 [APP/PROC/WEB/0]ERR npm ERR! 
2019-08-23T14:00:56.17-0700 [APP/PROC/WEB/0]ERR npm ERR! Failed at the watson-banking-chatbot@0.0.1 start script.
2019-08-23T14:00:56.17-0700 [APP/PROC/WEB/0]ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-08-23T14:00:56.20-0700 [APP/PROC/WEB/0]ERR npm ERR! A complete log of this run can be found in:
2019-08-23T14:00:56.20-0700 [APP/PROC/WEB/0]ERR npm ERR!     /home/vcap/app/.npm/_logs/2019-08-23T21_00_56_175Z-debug.log

**Comment by markstur** [comment]
I'll work on this.  There's a different deploy issue now.

**Comment by markstur** [comment]
Fixed in #123
