### ISSUE TITLE
Error: Missing required parameters: apikey

### ISSUE THREAD

**Issue by Chofoteddy** [IBM/watson-banking-chatbot#154]
I followed every step described in the README file to deploy it locally, env file is the only one that I've modified in order to put the key values of the data requested:

- ASSISTANT_AUTH_TYPE
- ASSISTANT_APIKEY
- ASSISTANT_URL
- SKILL_ID

- NATURAL_LANGUAGE_UNDERSTANDING_AUTH_TYPE
- NATURAL_LANGUAGE_UNDERSTANDING_APIKEY
- NATURAL_LANGUAGE_UNDERSTANDING_URL

- DISCOVERY_AUTH_TYPE
- DISCOVERY_APIKEY
- DISCOVERY_URL
- DISCOVERY_ENVIRONMENT_ID
- DISCOVERY_COLLECTION_ID

Then I run `npm install` and `npm start`:

```
Error: Missing required parameters: apikey
    at Object.getMissingParams (/Users/myuser/behind/watson-banking-chatbot/node_modules/ibm-cloud-sdk-core/lib/helper.js:102:11)
    at Object.validateInput (/Users/myuser/behind/watson-banking-chatbot/node_modules/ibm-cloud-sdk-core/auth/utils/helpers.js:61:39)
    at new IamAuthenticator (/Users/myuser/behind/watson-banking-chatbot/node_modules/ibm-cloud-sdk-core/auth/authenticators/iam-authenticator.js:47:17)
    at getAuthenticatorFromEnvironment (/Users/myuser/behind/watson-banking-chatbot/node_modules/ibm-cloud-sdk-core/auth/utils/get-authenticator-from-environment.js:63:29)
    at Object.<anonymous> (/Users/myuser/behind/watson-banking-chatbot/app.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
```

I even tried to do it again (deleting repo), but the same result is printed.

**Comment by Chofoteddy** [comment]
Dah! sorry, I found that my env file was wrong named.
